# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistroyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('app', models.CharField(default=b'', max_length=64)),
                ('model_name', models.CharField(default=b'', max_length=64)),
                ('model_pk', models.IntegerField(default=-1)),
                ('snap', models.CharField(default=b'', help_text='\u5feb\u7167', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
