# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_histroymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='histroymodel',
            name='action',
            field=models.CharField(default=b'', max_length=32),
        ),
    ]
