# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='\u6fc0\u6d3b')),
                ('permission', models.TextField(blank=True, default=b'{}', verbose_name='\u6743\u9650')),
                ('config', models.TextField(blank=True, default=b'{}', verbose_name='\u4e2a\u4eba\u914d\u7f6e')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS\u914d\u7f6e',
            },
        ),
    ]
